#!/usr/bin/env bash
set -euo pipefail

export ANARTZ_DIST="bookworm"
export ANARTZ_ARCH="amd64"
export ANARTZ_MIRROR="http://deb.debian.org/debian"
export ANARTZ_SECURITY_MIRROR="http://security.debian.org/debian-security"
export ANARTZ_PROFILES="anartz"
export ANARTZ_ISO_NAME="anartz-os-installable.iso"

echo "[INFO] Configuración Anartz OS cargada: dist=${ANARTZ_DIST}, arch=${ANARTZ_ARCH}, profile=${ANARTZ_PROFILES}"
